source production/.env.$ENVIRONMENT

vercel env rm -y GRAPHQL_ENDPOINT $ENVIRONMENT
echo $GRAPHQL_ENDPOINT
echo $GRAPHQL_ENDPOINT | vercel env add GRAPHQL_ENDPOINT $ENVIRONMENT 

vercel env rm -y DATABASE_URL $ENVIRONMENT
echo $DATABASE_URL
echo $DATABASE_URL | vercel env add DATABASE_URL $ENVIRONMENT 

vercel env rm -y HASURA_ADMIN_SECRET $ENVIRONMENT
echo $HASURA_ADMIN_SECRET
echo $HASURA_ADMIN_SECRET | vercel env add HASURA_ADMIN_SECRET $ENVIRONMENT 

vercel env rm -y NEXTAUTH_URL $ENVIRONMENT
echo $NEXTAUTH_URL
echo $NEXTAUTH_URL | vercel env add NEXTAUTH_URL $ENVIRONMENT 

vercel env rm -y JWT_SECRET $ENVIRONMENT
echo $JWT_SECRET
echo $JWT_SECRET | vercel env add JWT_SECRET $ENVIRONMENT 

vercel env rm -y AWS_ACCESS_KEY_ID_APP $ENVIRONMENT
echo $AWS_ACCESS_KEY_ID_APP
echo $AWS_ACCESS_KEY_ID_APP | vercel env add AWS_ACCESS_KEY_ID_APP $ENVIRONMENT 

vercel env rm -y AWS_SECRET_ACCESS_KEY_APP $ENVIRONMENT
echo $AWS_SECRET_ACCESS_KEY_APP
echo $AWS_SECRET_ACCESS_KEY_APP | vercel env add AWS_SECRET_ACCESS_KEY_APP $ENVIRONMENT 

vercel env rm -y EMAIL_FROM $ENVIRONMENT
echo $EMAIL_FROM
echo $EMAIL_FROM | vercel env add EMAIL_FROM $ENVIRONMENT 

vercel env rm -y EMAIL_SERVER_PORT $ENVIRONMENT
echo $EMAIL_SERVER_PORT
echo $EMAIL_SERVER_PORT | vercel env add EMAIL_SERVER_PORT $ENVIRONMENT 

vercel env rm -y EMAIL_SERVER_HOST $ENVIRONMENT
echo $EMAIL_SERVER_HOST
echo $EMAIL_SERVER_HOST | vercel env add EMAIL_SERVER_HOST $ENVIRONMENT 

vercel env rm -y EMAIL_SERVER_PASSWORD $ENVIRONMENT
echo $EMAIL_SERVER_PASSWORD
echo $EMAIL_SERVER_PASSWORD | vercel env add EMAIL_SERVER_PASSWORD $ENVIRONMENT 

vercel env rm -y EMAIL_SERVER_USER $ENVIRONMENT
echo $EMAIL_SERVER_USER
echo $EMAIL_SERVER_USER | vercel env add EMAIL_SERVER_USER $ENVIRONMENT 

vercel env rm -y SITE $ENVIRONMENT
echo $SITE
echo $SITE | vercel env add SITE $ENVIRONMENT 

vercel env rm -y GOOGLE_CLIENT_SECRET $ENVIRONMENT
echo $GOOGLE_CLIENT_SECRET
echo $GOOGLE_CLIENT_SECRET | vercel env add GOOGLE_CLIENT_SECRET $ENVIRONMENT 

vercel env rm -y GOOGLE_CLIENT_ID $ENVIRONMENT
echo $GOOGLE_CLIENT_ID
echo $GOOGLE_CLIENT_ID | vercel env add GOOGLE_CLIENT_ID $ENVIRONMENT 

