source production/.env.$ENVIRONMENT

vercel env rm -y GRAPHQL_ENDPOINT $ENVIRONMENT
echo "GRAPHQL_ENDPOINT $GRAPHQL_ENDPOINT"
printf %s $GRAPHQL_ENDPOINT | vercel env add GRAPHQL_ENDPOINT $ENVIRONMENT

vercel env rm -y DATABASE_URL $ENVIRONMENT
echo "DATABASE_URL $DATABASE_URL"
printf %s $DATABASE_URL | vercel env add DATABASE_URL $ENVIRONMENT

vercel env rm -y HASURA_ADMIN_SECRET $ENVIRONMENT
echo "HASURA_ADMIN_SECRET $HASURA_ADMIN_SECRET"
printf %s $HASURA_ADMIN_SECRET | vercel env add HASURA_ADMIN_SECRET $ENVIRONMENT

vercel env rm -y NEXTAUTH_URL $ENVIRONMENT
echo "NEXTAUTH_URL $NEXTAUTH_URL"
printf %s $NEXTAUTH_URL | vercel env add NEXTAUTH_URL $ENVIRONMENT

vercel env rm -y JWT_SECRET $ENVIRONMENT
echo "JWT_SECRET $JWT_SECRET"
printf %s $JWT_SECRET | vercel env add JWT_SECRET $ENVIRONMENT

vercel env rm -y AWS_ACCESS_KEY_ID_APP $ENVIRONMENT
echo "AWS_ACCESS_KEY_ID_APP $AWS_ACCESS_KEY_ID_APP"
printf %s $AWS_ACCESS_KEY_ID_APP | vercel env add AWS_ACCESS_KEY_ID_APP $ENVIRONMENT

vercel env rm -y AWS_SECRET_ACCESS_KEY_APP $ENVIRONMENT
echo "AWS_SECRET_ACCESS_KEY_APP $AWS_SECRET_ACCESS_KEY_APP"
printf %s $AWS_SECRET_ACCESS_KEY_APP | vercel env add AWS_SECRET_ACCESS_KEY_APP $ENVIRONMENT

vercel env rm -y EMAIL_FROM $ENVIRONMENT
echo "EMAIL_FROM $EMAIL_FROM"
printf %s $EMAIL_FROM | vercel env add EMAIL_FROM $ENVIRONMENT

vercel env rm -y EMAIL_SERVER_PORT $ENVIRONMENT
echo "EMAIL_SERVER_PORT $EMAIL_SERVER_PORT"
printf %s $EMAIL_SERVER_PORT | vercel env add EMAIL_SERVER_PORT $ENVIRONMENT

vercel env rm -y EMAIL_SERVER_HOST $ENVIRONMENT
echo "EMAIL_SERVER_HOST $EMAIL_SERVER_HOST"
printf %s $EMAIL_SERVER_HOST | vercel env add EMAIL_SERVER_HOST $ENVIRONMENT

vercel env rm -y EMAIL_SERVER_PASSWORD $ENVIRONMENT
echo "EMAIL_SERVER_PASSWORD $EMAIL_SERVER_PASSWORD"
printf %s $EMAIL_SERVER_PASSWORD | vercel env add EMAIL_SERVER_PASSWORD $ENVIRONMENT

vercel env rm -y EMAIL_SERVER_USER $ENVIRONMENT
echo "EMAIL_SERVER_USER $EMAIL_SERVER_USER"
printf %s $EMAIL_SERVER_USER | vercel env add EMAIL_SERVER_USER $ENVIRONMENT

vercel env rm -y GOOGLE_CLIENT_SECRET $ENVIRONMENT
echo "GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET"
printf %s $GOOGLE_CLIENT_SECRET | vercel env add GOOGLE_CLIENT_SECRET $ENVIRONMENT

vercel env rm -y GOOGLE_CLIENT_ID $ENVIRONMENT
echo "GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID"
printf %s $GOOGLE_CLIENT_ID | vercel env add GOOGLE_CLIENT_ID $ENVIRONMENT

