source production/.env.$ENVIRONMENT

vercel env rm -y GRAPHQL_ENDPOINT $ENVIRONMENT
echo "GRAPHQL_ENDPOINT $GRAPHQL_ENDPOINT"
vercel env add GRAPHQL_ENDPOINT $ENVIRONMENT <<< $GRAPHQL_ENDPOINT

vercel env rm -y DATABASE_URL $ENVIRONMENT
echo "DATABASE_URL $DATABASE_URL"
vercel env add DATABASE_URL $ENVIRONMENT <<< $DATABASE_URL

vercel env rm -y HASURA_ADMIN_SECRET $ENVIRONMENT
echo "HASURA_ADMIN_SECRET $HASURA_ADMIN_SECRET"
vercel env add HASURA_ADMIN_SECRET $ENVIRONMENT <<< $HASURA_ADMIN_SECRET

vercel env rm -y NEXTAUTH_URL $ENVIRONMENT
echo "NEXTAUTH_URL $NEXTAUTH_URL"
vercel env add NEXTAUTH_URL $ENVIRONMENT <<< $NEXTAUTH_URL

vercel env rm -y JWT_SECRET $ENVIRONMENT
echo "JWT_SECRET $JWT_SECRET"
vercel env add JWT_SECRET $ENVIRONMENT <<< $JWT_SECRET

vercel env rm -y AWS_ACCESS_KEY_ID_APP $ENVIRONMENT
echo "AWS_ACCESS_KEY_ID_APP $AWS_ACCESS_KEY_ID_APP"
vercel env add AWS_ACCESS_KEY_ID_APP $ENVIRONMENT <<< $AWS_ACCESS_KEY_ID_APP

vercel env rm -y AWS_SECRET_ACCESS_KEY_APP $ENVIRONMENT
echo "AWS_SECRET_ACCESS_KEY_APP $AWS_SECRET_ACCESS_KEY_APP"
vercel env add AWS_SECRET_ACCESS_KEY_APP $ENVIRONMENT <<< $AWS_SECRET_ACCESS_KEY_APP

vercel env rm -y EMAIL_FROM $ENVIRONMENT
echo "EMAIL_FROM $EMAIL_FROM"
vercel env add EMAIL_FROM $ENVIRONMENT <<< $EMAIL_FROM

vercel env rm -y EMAIL_SERVER_PORT $ENVIRONMENT
echo "EMAIL_SERVER_PORT $EMAIL_SERVER_PORT"
vercel env add EMAIL_SERVER_PORT $ENVIRONMENT <<< $EMAIL_SERVER_PORT

vercel env rm -y EMAIL_SERVER_HOST $ENVIRONMENT
echo "EMAIL_SERVER_HOST $EMAIL_SERVER_HOST"
vercel env add EMAIL_SERVER_HOST $ENVIRONMENT <<< $EMAIL_SERVER_HOST

vercel env rm -y EMAIL_SERVER_PASSWORD $ENVIRONMENT
echo "EMAIL_SERVER_PASSWORD $EMAIL_SERVER_PASSWORD"
vercel env add EMAIL_SERVER_PASSWORD $ENVIRONMENT <<< $EMAIL_SERVER_PASSWORD

vercel env rm -y EMAIL_SERVER_USER $ENVIRONMENT
echo "EMAIL_SERVER_USER $EMAIL_SERVER_USER"
vercel env add EMAIL_SERVER_USER $ENVIRONMENT <<< $EMAIL_SERVER_USER

vercel env rm -y GOOGLE_CLIENT_SECRET $ENVIRONMENT
echo "GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET"
vercel env add GOOGLE_CLIENT_SECRET $ENVIRONMENT <<< $GOOGLE_CLIENT_SECRET

vercel env rm -y GOOGLE_CLIENT_ID $ENVIRONMENT
echo "GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID"
vercel env add GOOGLE_CLIENT_ID $ENVIRONMENT <<< $GOOGLE_CLIENT_ID

