source production/.env.$ENVIRONMENT

rm temp
touch temp

echo "GRAPHQL_ENDPOINT $GRAPHQL_ENDPOINT"
echo <<< $GRAPHQL_ENDPOINT

echo "DATABASE_URL $DATABASE_URL"
echo <<< $DATABASE_URL

echo "HASURA_ADMIN_SECRET $HASURA_ADMIN_SECRET"
echo <<< $HASURA_ADMIN_SECRET