version: 2
endpoint: http://app.arbo.link:8080/
admin_secret: myadminsecretkey
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: https://app.arboreum.dev
show_update_notification: false
