version: 2
endpoint: https://fine-finch-84.hasura.app/
admin_secret: T4AwDcyGfKLakMj
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: https://app.arboreum.dev
show_update_notification: false
