version: 2
endpoint: http://app.arbo.link:8075/
admin_secret: arbo_secret_hasura_gs
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: https://app.arboreum.dev
show_update_notification: false
