version: 2
endpoint: http://dev1.arbo.link/v1/graphql
admin_secret: myadminsecretkey
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: https://app.arboreum.dev
show_update_notification: false
